# This Workflow builds a docker image using the production Dockerfile and deploys it to Google Cloud Run.
# It will only run if the repo is dpgraham-com/dpgraham-client and triggered by a published release.

name: On Release

on:
  release:
    types: [ published ]

jobs:
  build_gcp_image:
    if: github.repository == 'dpgraham-com/dpgraham-client'
    name: Build Image for Production
    uses: ./.github/workflows/build-gcp-image.yaml
    with:
      environment: production
    secrets: inherit

  deploy_to_cloud_run:
    if: github.repository == 'dpgraham-com/dpgraham-client'
    name: Deploy to Cloud Run
    uses: ./.github/workflows/cloud-run-deploy.yaml
    needs: build_gcp_image
    with:
      environment: production
      version: ${{ needs.build_gcp_image.outputs.version }}
      service: dpgraham-frontend
    secrets: inherit

  build_ghcr_image:
    name: Build Image for GHCR
    uses: ./.github/workflows/build-ghcr-image.yaml
    secrets: inherit