# This Workflow builds a docker image using the development Dockerfile and deploys it to Google Cloud Run.
# It will only run if the repo is dpgraham-com/dpgraham-client and the branch is main.

name: Deploy to Development Environment

on:
  push:
#      branches:
#      - main

jobs:
  build_gcp_image:
    if: github.repository == 'dpgraham-com/dpgraham-client'
    permissions:
      id-token: write
      contents: read
    name: Build Image for Development
    uses: ./.github/workflows/build-gcp-image.yaml
    with:
      environment: development
    secrets: inherit

#  deploy_to_cloud_run:
#    if: github.repository == 'dpgraham-com/dpgraham-client'
#    name: Deploy to Cloud Run
#    uses: ./.github/workflows/cloud-run-deploy.yaml
#    needs: build_gcp_image
#    with:
#      environment: development
#      version: ${{ needs.build_gcp_image.outputs.version }}
#      service: dpgraham-frontend
#    secrets: inherit
